# Generated by Django 4.2.16 on 2024-10-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elim_Gauss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EG_matriz', models.JSONField()),
                ('EG_resultado', models.JSONField(blank=True, null=True)),
                ('EG_ecuaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultiFxC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mfc_Fila', models.JSONField()),
                ('Mfc_Column', models.JSONField()),
                ('Mfc_resultado', models.JSONField()),
                ('Mfc_ecuaciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ope_combinadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OpV_vectores', models.JSONField()),
                ('OpV_escalares', models.JSONField()),
                ('OpV_resultado', models.JSONField()),
                ('OpV_ecuaciones', models.TextField()),
            ],
        ),
    ]
