# Generated by Django 4.2.16 on 2024-10-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eliminacionGauss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropMxV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pMxV_matrix', models.JSONField()),
                ('pMxV_vectorU', models.JSONField()),
                ('pMxV_vectorV', models.JSONField()),
                ('pMxV_resultado', models.JSONField()),
                ('pMxV_ecuaciones', models.TextField()),
            ],
        ),
    ]
