# Generated by Django 4.2.16 on 2024-10-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eliminacionGauss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elim_gauss',
            name='EG_tabla_id',
            field=models.IntegerField(),
        ),
    ]
