# Generated by Django 4.2.16 on 2024-10-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eliminacionGauss', '0002_propmxv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multifxc',
            name='Mfc_ecuaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='multifxc',
            name='Mfc_resultado',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ope_combinadas',
            name='OpV_ecuaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ope_combinadas',
            name='OpV_resultado',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propmxv',
            name='pMxV_ecuaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propmxv',
            name='pMxV_resultado',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
