# Generated by Django 4.2.16 on 2024-10-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eliminacionGauss', '0003_alter_multifxc_mfc_ecuaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmMrx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sMrx_matrxS', models.JSONField()),
                ('sMrx_escalares', models.JSONField()),
                ('sMrx_resultado', models.JSONField(blank=True, null=True)),
                ('sMrx_ecuaciones', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
