# Generated by Django 4.2.16 on 2024-11-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eliminacionGauss', '0004_smmrx'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrnsMtx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trMx_Matriz', models.JSONField()),
                ('trMx_resultado', models.JSONField(blank=True, null=True)),
                ('trMx_ecuaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
