# Generated by Django 4.2.16 on 2024-11-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eliminacionGauss', '0006_clcdeterm_multmtrx'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvMtrx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmx_Matrx', models.JSONField()),
                ('inmx_resultado', models.JSONField(blank=True, null=True)),
                ('inmx_ecuaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
