# Generated by Django 4.2.16 on 2024-11-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eliminacionGauss', '0007_invmtrx'),
    ]

    operations = [
        migrations.CreateModel(
            name='factLU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lu_mtrx', models.JSONField()),
                ('lu_resultado', models.JSONField(blank=True, null=True)),
                ('lu_ecuaciones', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RglCramer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cramer_Matrx', models.JSONField()),
                ('cramer_TermsIndp', models.JSONField()),
                ('cramer_resultado', models.JSONField(blank=True, null=True)),
                ('cramer_ecuaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
