# Generated by Django 4.2.16 on 2024-11-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eliminacionGauss', '0009_remove_rglcramer_cramer_termsindp'),
    ]

    operations = [
        migrations.CreateModel(
            name='biSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bi_funcion', models.TextField()),
                ('bi_resultado', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
