# Generated by Django 4.2.16 on 2024-11-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eliminacionGauss', '0011_remove_biseccion_bi_ab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biseccion',
            name='bi_funcion',
            field=models.JSONField(),
        ),
    ]
